FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install deps first (cached layer)
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy app code (but in dev we mount this as a volume instead)
COPY . .

EXPOSE 3000

# Run in dev mode (hot reload)
CMD ["yarn", "dev", "--host"]
