FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install deps first (cached layer)
COPY package.json yarn.lock ./
# Increase Yarn network timeout and ensure registry is set before install
RUN yarn config set network-timeout 600000 && \
	yarn config set registry https://registry.yarnpkg.com && \
	yarn install

# Copy app code (but in dev we mount this as a volume instead)
COPY . .

EXPOSE 3000

# Run in dev mode (hot reload)
CMD ["yarn", "dev", "--host"]
